### ISSUE TITLE
Frontend bug

### ISSUE THREAD

**Issue by Jason011125** [cse110-fa22-group38/cse110-fa22-group38#15]
Check img below, weird zoom under 100% on my 13 inch mac
<img width="1440" alt="截屏2022-11-04 下午1 23 28" src="https://user-images.githubusercontent.com/83381717/200068015-83a7ad6f-f684-414b-b0c1-1f6e21bfa7f6.png">

**Comment by jpaoad31** [comment]
Fixed for the most part. Of course, the view still breaks on extremely small page sizes (what page doesn't), but it is usable at a significantly more page sizes.

**Comment by jpaoad31** [comment]
Let me know if this is still an issue.
